# Generated by Django 4.2.5 on 2023-10-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_libraian',
            field=models.BooleanField(default=False),
        ),
    ]
