# Generated by Django 5.1.1 on 2024-10-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_first_name_remove_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
