# Generated by Django 5.1.1 on 2024-10-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
