# Generated by Django 4.2.5 on 2023-10-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_libraian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_libraian',
            new_name='is_librarian',
        ),
    ]
