# Generated by Django 4.2.5 on 2024-01-23 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 1, 23, 8, 56, 2, 620793, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='gmap',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
