# Generated by Django 4.2.5 on 2024-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_institution_date_joined_institution_gmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='gmap',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
