# Generated by Django 4.2.5 on 2024-01-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_institution_gmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
