# Generated by Django 4.2.10 on 2024-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_institution_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
