# Generated by Django 4.2.10 on 2024-02-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account__name_account_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='_name',
            new_name='last_name',
        ),
    ]
