# Generated by Django 4.2.5 on 2023-09-23 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('series', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=200, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Publisher Location')),
                ('call_number', models.CharField(blank=True, max_length=200, verbose_name='Call Number')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution Hosted')),
                ('year_published', models.DateField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Book Catalogue',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
