# Generated by Django 5.1.1 on 2024-10-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('edition', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=200, verbose_name='ISBN')),
                ('call_no', models.CharField(blank=True, max_length=200, verbose_name='Call Number')),
                ('place_of_publication', models.CharField(blank=True, max_length=200, verbose_name='Publisher Location')),
                ('year_published', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('edited', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('institution', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
            options={
                'verbose_name_plural': 'Book Catalogue',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalogue/uploads/')),
                ('added', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
            options={
                'verbose_name_plural': 'Excel Upload',
            },
        ),
    ]
