# Generated by Django 4.2.5 on 2023-10-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('series', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=200, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Publisher Location')),
                ('call_number', models.CharField(blank=True, max_length=200, verbose_name='Call Number')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution Hosted')),
                ('year_published', models.DateField()),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Book Catalogue',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='catalogue/uploads/')),
                ('added', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
            options={
                'verbose_name_plural': 'Excel Upload',
            },
        ),
    ]
