# Generated by Django 5.1.1 on 2024-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
