# Generated by Django 4.2.10 on 2024-02-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
