# Generated by Django 4.2.5 on 2023-09-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={'verbose_name_plural': 'Excel Upload'},
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='institution',
        ),
        migrations.AddField(
            model_name='excelupload',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution'),
        ),
    ]
