# Generated by Django 5.1.1 on 2024-10-22 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partners', '0002_institution_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name_plural': 'Library Books'},
        ),
        migrations.AlterModelOptions(
            name='excelupload',
            options={'verbose_name_plural': 'Library Upload'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='Nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='call_no',
            field=models.CharField(blank=True, default='Nil', max_length=200, verbose_name='Call Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, default='Nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='partners.institution'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='Nil', max_length=200, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='place_of_publication',
            field=models.CharField(blank=True, default='Nil', max_length=200, verbose_name='Publisher Location'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='Nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='Nil', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, default='Nil', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, default='Nil', max_length=4),
        ),
    ]
