# Generated by Django 4.2.10 on 2024-03-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='series',
            new_name='edition',
        ),
    ]
