# Generated by Django 5.1.1 on 2024-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_book_options_alter_excelupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='call_no',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True, verbose_name='Call Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True, verbose_name='ISBN'),
        ),
    ]
