# Generated by Django 5.1.1 on 2024-10-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_book_call_no_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='place_of_publication',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True, verbose_name='Publisher Location'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, default='Nil', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.CharField(blank=True, default='Nil', max_length=4, null=True),
        ),
    ]
